version: "3"
services:
  cartola:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    restart: always
    container_name: cartola
    hostname: cartola
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    networks:
      - cartola

volumes:
  postgres_volume:

networks:
  cartola:
